version: '3.8'

services:
  simple-service:
    build: .
    image: simple-service:latest
    ports:
      - "8111:8111"
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "8080:80"
    
    depends_on:
      - simple-service