version: '3.8'

services:
  simple-service:
    build: .
    image: simple-service:latest
    ports:
      - "8111"
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - simple-service